# Generated by Django 5.2.1 on 2025-05-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderDate',
            new_name='order_date',
        ),
    ]
